name: anslin
description: "避難所アプリ"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  permission_handler: ^12.0.1
  url_launcher: ^6.3.2
  sqflite: ^2.4.2
  badges: ^3.1.2 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/img/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/app_icon.png"
  adaptive_icon_background: "#73e8a8" 
  adaptive_icon_foreground: "assets/img/app_icon.png"
